"""
Core Domain Models and Value Objects for Continuous Legal Memory.

This module defines immutable value objects and dataclasses representing legal memory items,
prediction outputs, and metadata necessary for temporal tracking, attestation, and neural memory routing.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

import torch


@dataclass
class MemoryRecord:
    """
    Immutable value object representing a single legal memory record node.

    Attributes:
        text: Raw textual representation of the legal statute, rule, or client preference.
        key_vector: Key embedding tensor generated by the semantic encoder.
        value_vector: Action/decision output target vector mapping to legal decisions.
        importance_score: Dynamic surprise-weighted importance factor for override precedence.
        record_id: Unique string identifier for indexing and cryptographic auditing.
        valid_from: Datetime timestamp marking the start of temporal validity.
        valid_to: Optional datetime timestamp marking when the rule expires or is invalidated.
        metadata: Arbitrary key-value store for compliance tags (e.g., GDPR Art. 17 audit trails).
    """

    text: str
    key_vector: torch.Tensor
    value_vector: torch.Tensor
    importance_score: float = 1.0
    record_id: str | None = None
    valid_from: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    valid_to: datetime | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    def is_temporally_valid(self, at_time: datetime | None = None) -> bool:
        """
        Check if the memory record is valid at a given timestamp.

        Args:
            at_time: The timestamp to evaluate validity against. Defaults to current UTC time.

        Returns:
            True if the record is currently valid; False if it has expired.
        """
        check_time = at_time or datetime.now(timezone.utc)
        if check_time < self.valid_from:
            return False
        return not (self.valid_to is not None and check_time > self.valid_to)


@dataclass
class PredictionResult:
    """
    Data transfer object representing the result of a legal memory prediction query.

    Attributes:
        query: The input query string submitted for evaluation.
        predicted_action_vector: List of floating-point decision values output by the memory network.
        most_relevant_rule: Text snippet of the top-matching memory rule, if memory is populated.
        confidence: Attention score (0.0 to 1.0) indicating model retrieval confidence.
        fast_slow_gate: Dynamic gating coefficient routing emphasis between short-term fast adaptation
                        and long-term slow consolidation networks.
        attention_weights: Full list of attention weights across all stored memory records.
    """

    query: str
    predicted_action_vector: list[float]
    most_relevant_rule: str | None = None
    confidence: float | None = None
    fast_slow_gate: float | None = None
    attention_weights: list[float] | None = None
